name: Build and Deploy

on:
  push:
    branches:
      - development # Or whichever branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install
      - name: Build for production
        run: yarn build
      - name: Push to Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./build
          publish_branch: pages


